"""add index

Revision ID: 9d7c9a36822c
Revises: 
Create Date: 2020-11-07 10:38:01.535758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7c9a36822c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit', sa.String(length=100), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_to_do_goal'), 'to_do', ['goal'], unique=False)
    op.create_index(op.f('ix_to_do_habit'), 'to_do', ['habit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_to_do_habit'), table_name='to_do')
    op.drop_index(op.f('ix_to_do_goal'), table_name='to_do')
    op.drop_table('to_do')
    # ### end Alembic commands ###
